# Generated by Django 5.2.16 on 2026-08-05 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0010_auto_20260724_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsocevent',
            name='rcvr_station',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)'), (101, 'User Interface')], null=True),
        ),
        migrations.AddField(
            model_name='dsocevent',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ready'), (2, 'Queued'), (3, 'Blocked'), (4, 'Transferring'), (5, 'Verifying'), (6, 'Transferred'), (7, 'Failed'), (8, 'Completed')], null=True),
        ),
        migrations.AddField(
            model_name='dsocevent',
            name='transfer_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dsocevent',
            name='xmit_station',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)'), (101, 'User Interface')], null=True),
        ),
        migrations.AddField(
            model_name='observatoryevent',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ready'), (2, 'Queued'), (3, 'Blocked'), (4, 'Transferring'), (5, 'Verifying'), (6, 'Transferred'), (7, 'Failed'), (8, 'Completed')], null=True),
        ),
        migrations.AddField(
            model_name='observatoryevent',
            name='transfer_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='object_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='rcvr_station',
            field=models.IntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)'), (101, 'User Interface')], null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='station',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)'), (101, 'User Interface')], default=9, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observatoryevent',
            name='xmit_station',
            field=models.IntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)'), (101, 'User Interface')], null=True),
        ),
        migrations.CreateModel(
            name='ETransferEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_uuid', models.UUIDField(db_index=True, editable=False)),
                ('gbt_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('station', models.PositiveSmallIntegerField(blank=True, choices=[(9, 'Green Bank (100-m, GBT)'), (90, 'St. Croix (25-m, VLBA)'), (91, 'Hancock (25-m, VLBA)'), (92, 'North Liberty (25-m, VLBA)'), (93, 'Fort Davis (25-m, VLBA)'), (94, 'Los Alamos (25-m, VLBA)'), (95, 'Pie Town (25-m, VLBA)'), (96, 'Kitt Peak (25-m, VLBA)'), (97, 'Owens Valley (25-m, VLBA)'), (98, 'Brewster (25-m, VLBA)'), (99, 'Mauna Kea (25-m, VLBA)'), (100, 'DSOC (Domenici Socorro Operations Center)'), (101, 'User Interface')], null=True)),
                ('event_time', models.DateTimeField()),
                ('latency_ms', models.FloatField(default=0.0)),
                ('num_bytes', models.BigIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ready'), (2, 'Queued'), (3, 'Blocked'), (4, 'Transferring'), (5, 'Verifying'), (6, 'Transferred'), (7, 'Failed'), (8, 'Completed')])),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['event_time'],
                'indexes': [models.Index(fields=['transfer_uuid', 'event_time'], name='ngRadar_Web_transfe_c5bd1e_idx')],
            },
        ),
    ]
