# Generated by Django 5.2.17 on 2026-08-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngRadar_Website', '0011_dsocevent_rcvr_station_dsocevent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsocevent',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='observatoryevent',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='etransferevent',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
